FROM golang:1.19.3-alpine3.16 as builder

ADD ./ /app
WORKDIR /app
RUN go get -d -v .
RUN go build

FROM alpine:3.16.2
WORKDIR /root/
COPY --from=builder /app ./
CMD ["/bin/sh", "-c", "sleep 10 && ./car-park"]
EXPOSE 8888